14 ВАРИАНТ 

№ 32. Используя модуль array и библиотеку numpy, решить следующие задачи:
а) Дано множество  A  из  N  точек (точки заданы своими координатами  x ,  y ). Для хранения данных о каждом наборе точек следует использовать по два массива: первый массив для хранения абсцисс, второй — для хранения ординат. Среди всех точек этого множества, лежащих во второй четверти, найти точку, наиболее удаленную от начала координат. Если таких точек нет, то вывести точку с нулевыми координатами.
б) Дана матрица размера  M×N . Элемент матрицы называется ее локальным максимумом, если он больше всех окружающих его элементов. Поменять знак всех локальных максимумов данной матрицы на противоположный.

In [17]:
import numpy as np

In [18]:
#a)
# Генерация случайных координат для точек
N = 10
x_coords = np.random.randint(-10, 10, N)
y_coords = np.random.randint(-10, 10, N)

# Нахождение точек во второй четверти
second_quadrant_points = [(x, y) for x, y in zip(x_coords, y_coords) if x < 0 and y > 0]

if second_quadrant_points:
    max_distance_point = max(second_quadrant_points, key=lambda point: point[0]**2 + point[1]**2)
    print(f"Наиболее удаленная от начала координат точка во второй четверти: {max_distance_point}")
else:
    print("Нет точек во второй четверти, выводим точку с нулевыми координатами: (0, 0)")


Наиболее удаленная от начала координат точка во второй четверти: (-6, 2)


In [19]:
#b)
# Генерация случайной матрицы
M, N = 5, 5
matrix = np.random.randint(1, 10, (M, N))

# Поиск локальных максимумов и изменение их знака
for i in range(1, M-1):
    for j in range(1, N-1):
        if matrix[i,j] > matrix[i-1,j] and matrix[i,j] > matrix[i+1,j] and matrix[i,j] > matrix[i,j-1] and matrix[i,j] > matrix[i,j+1]:
            matrix[i,j] *= -1

print("Матрица с измененными знаками локальных максимумов:")
print(matrix)


Матрица с измененными знаками локальных максимумов:
[[ 1  7  2  8  6]
 [ 9  8  6  8  9]
 [ 6  8  3  5  8]
 [ 6  2 -7  4  8]
 [ 5  9  5  5  3]]


№ 33. Дан стек. Необходимо проверить, является ли его содержимое последовательностью геометрической прогрессии.

In [11]:
stack = [2, 4, 8, 16, 32]

In [15]:
from collections import deque
def is_geom_prog(stack):
    if len(stack) < 2:
        return False
    
    q = stack[1] / stack[0] 
    
    for i in range(1, len(stack)-1):
        if stack[i+1] / stack[i] != q:
            return False
        
if is_geom_prog(stack):
    print("Содержимое стека не является геометрической прогрессией")
else:
    print("Содержимое стека является геометрической прогрессией")
        

Содержимое стека является геометрической прогрессией


№ 34. Создать класс очереди, который будет поддерживать операции добавления элемента в конец очереди и удаления всех элементов из очереди, которые больше заданного значения

In [16]:
class Queue:
    def __init__(self):
        self.queue = []

    def enqueue(self, value):
        self.queue.append(value)

    def dequeue(self):
        if not self.is_empty():
            return self.queue.pop(0)
        else:
            return None

    def is_empty(self):
        return len(self.queue) == 0

    def remove_greater_than(self, value):
        self.queue = [x for x in self.queue if x <= value]

    def print_queue(self):
        print(self.queue)

q = Queue()
q.enqueue(5)
q.enqueue(10)
q.enqueue(15)
q.enqueue(20)

print("Очередь до удаления:")
q.print_queue()

value_to_remove = 12
q.remove_greater_than(value_to_remove)

print(f"Удаляем элементы больше {value_to_remove}:")
q.print_queue()


Очередь до удаления:
[5, 10, 15, 20]
Удаляем элементы больше 12:
[5, 10]
